namespace UmbracoCms.Web.Helpers.Aliases;

/// <summary>
/// CSS breakpoint definitions.
/// Previously generated by DEPT.Umbraco.SourceGenerators.
/// </summary>
public class CssBreakpoint
{
    public required string Name { get; init; }
    public int? Start { get; init; }
    public int? End { get; init; }
    public int? Priority { get; init; }
}

public static class CssBreakpoints
{
    private static readonly Dictionary<string, CssBreakpoint> Breakpoints = new(StringComparer.OrdinalIgnoreCase)
    {
        ["xs"] = new CssBreakpoint { Name = "xs", Start = null, End = 575, Priority = 0 },
        ["sm"] = new CssBreakpoint { Name = "sm", Start = 576, End = 767, Priority = 1 },
        ["md"] = new CssBreakpoint { Name = "md", Start = 768, End = 991, Priority = 2 },
        ["lg"] = new CssBreakpoint { Name = "lg", Start = 992, End = 1199, Priority = 3 },
        ["xl"] = new CssBreakpoint { Name = "xl", Start = 1200, End = null, Priority = 4 },
    };

    public static CssBreakpoint? GetBreakpoint(string name)
    {
        return Breakpoints.GetValueOrDefault(name);
    }
}
