namespace UmbracoCms.Web.Helpers.Aliases;

/// <summary>
/// Static aliases for favicon file paths.
/// Previously generated by DEPT.Umbraco.SourceGenerators.
/// </summary>
public static class FaviconAliases
{
    public const string FaviconIco = "/assets/favicons/favicon.ico";
    public const string Favicon16X16Png = "/assets/favicons/favicon-16x16.png";
    public const string Favicon32X32Png = "/assets/favicons/favicon-32x32.png";
    public const string Favicon48X48Png = "/assets/favicons/favicon-48x48.png";
    public const string Mstile144X144Png = "/assets/favicons/mstile-144x144.png";
    public const string BrowserconfigXml = "/assets/favicons/browserconfig.xml";
    public const string ManifestJson = "/assets/favicons/manifest.json";
    public const string AppleTouchIcon57X57Png = "/assets/favicons/apple-touch-icon-57x57.png";
    public const string AppleTouchIcon60X60Png = "/assets/favicons/apple-touch-icon-60x60.png";
    public const string AppleTouchIcon72X72Png = "/assets/favicons/apple-touch-icon-72x72.png";
    public const string AppleTouchIcon76X76Png = "/assets/favicons/apple-touch-icon-76x76.png";
    public const string AppleTouchIcon114X114Png = "/assets/favicons/apple-touch-icon-114x114.png";
    public const string AppleTouchIcon120X120Png = "/assets/favicons/apple-touch-icon-120x120.png";
    public const string AppleTouchIcon144X144Png = "/assets/favicons/apple-touch-icon-144x144.png";
    public const string AppleTouchIcon152X152Png = "/assets/favicons/apple-touch-icon-152x152.png";
    public const string AppleTouchIcon167X167Png = "/assets/favicons/apple-touch-icon-167x167.png";
    public const string AppleTouchIcon180X180Png = "/assets/favicons/apple-touch-icon-180x180.png";
    public const string AppleTouchIcon1024X1024Png = "/assets/favicons/apple-touch-icon-1024x1024.png";
    public const string AppleTouchStartupImage640X1136Png = "/assets/favicons/apple-touch-startup-image-640x1136.png";
    public const string AppleTouchStartupImage750X1334Png = "/assets/favicons/apple-touch-startup-image-750x1334.png";
    public const string AppleTouchStartupImage828X1792Png = "/assets/favicons/apple-touch-startup-image-828x1792.png";
    public const string AppleTouchStartupImage1125X2436Png = "/assets/favicons/apple-touch-startup-image-1125x2436.png";
    public const string AppleTouchStartupImage1242X2208Png = "/assets/favicons/apple-touch-startup-image-1242x2208.png";
    public const string AppleTouchStartupImage1242X2688Png = "/assets/favicons/apple-touch-startup-image-1242x2688.png";
    public const string AppleTouchStartupImage1536X2048Png = "/assets/favicons/apple-touch-startup-image-1536x2048.png";
    public const string AppleTouchStartupImage1668X2224Png = "/assets/favicons/apple-touch-startup-image-1668x2224.png";
    public const string AppleTouchStartupImage1668X2388Png = "/assets/favicons/apple-touch-startup-image-1668x2388.png";
    public const string AppleTouchStartupImage2048X2732Png = "/assets/favicons/apple-touch-startup-image-2048x2732.png";
    public const string AppleTouchStartupImage1620X2160Png = "/assets/favicons/apple-touch-startup-image-1620x2160.png";
    public const string AppleTouchStartupImage1136X640Png = "/assets/favicons/apple-touch-startup-image-1136x640.png";
    public const string AppleTouchStartupImage1334X750Png = "/assets/favicons/apple-touch-startup-image-1334x750.png";
    public const string AppleTouchStartupImage1792X828Png = "/assets/favicons/apple-touch-startup-image-1792x828.png";
    public const string AppleTouchStartupImage2436X1125Png = "/assets/favicons/apple-touch-startup-image-2436x1125.png";
    public const string AppleTouchStartupImage2208X1242Png = "/assets/favicons/apple-touch-startup-image-2208x1242.png";
    public const string AppleTouchStartupImage2688X1242Png = "/assets/favicons/apple-touch-startup-image-2688x1242.png";
    public const string AppleTouchStartupImage2048X1536Png = "/assets/favicons/apple-touch-startup-image-2048x1536.png";
    public const string AppleTouchStartupImage2224X1668Png = "/assets/favicons/apple-touch-startup-image-2224x1668.png";
    public const string AppleTouchStartupImage2388X1668Png = "/assets/favicons/apple-touch-startup-image-2388x1668.png";
    public const string AppleTouchStartupImage2732X2048Png = "/assets/favicons/apple-touch-startup-image-2732x2048.png";
    public const string AppleTouchStartupImage2160X1620Png = "/assets/favicons/apple-touch-startup-image-2160x1620.png";
}
