namespace UmbracoCms.Web.Helpers.Aliases;

/// <summary>
/// Static aliases for SVG file paths.
/// Previously generated by DEPT.Umbraco.SourceGenerators.
/// </summary>
public static class SvgAliases
{
    public const string Logo = "/assets/svg/logo.svg";

    public static class Social
    {
        public const string Facebook = "/assets/svg/social/facebook.svg";
        public const string Twitter = "/assets/svg/social/twitter.svg";
        public const string Linkedin = "/assets/svg/social/linkedin.svg";
        public const string Instagram = "/assets/svg/social/instagram.svg";
        public const string Youtube = "/assets/svg/social/youtube.svg";
        public const string Whatsapp = "/assets/svg/social/whatsapp.svg";
        public const string Email = "/assets/svg/social/email.svg";
    }
}
