namespace UmbracoCms.Web.Helpers.Aliases;

/// <summary>
/// Static aliases for Umbraco dictionary translation keys.
/// Previously generated by DEPT.Umbraco.SourceGenerators.
/// TranslationEntry is a simple string wrapper for translation keys.
/// </summary>
public sealed class TranslationEntry
{
    private readonly string _key;

    public TranslationEntry(string key) => _key = key;

    public static implicit operator string(TranslationEntry entry) => entry._key;

    public override string ToString() => _key;
}

public static class TranslationAliases
{
    public static class Common
    {
        public static class Breadcrumb
        {
            public static readonly TranslationEntry Label = new("Common.Breadcrumb.Label");
        }

        public static class Cookies
        {
            public static readonly TranslationEntry Accept = new("Common.Cookies.Accept");
            public static readonly TranslationEntry Save = new("Common.Cookies.Save");
        }

        public static class SocialSharing
        {
            public static readonly TranslationEntry Title = new("Common.SocialSharing.Title");
            public static readonly TranslationEntry Facebook = new("Common.SocialSharing.Facebook");
            public static readonly TranslationEntry Twitter = new("Common.SocialSharing.Twitter");
            public static readonly TranslationEntry Linkedin = new("Common.SocialSharing.Linkedin");
            public static readonly TranslationEntry Whatsapp = new("Common.SocialSharing.Whatsapp");
            public static readonly TranslationEntry Email = new("Common.SocialSharing.Email");
        }
    }
}
